apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-aqua-prom-db 
spec:
  storageClassName: ocs-storagecluster-ceph-rdb
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
