apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-aqua-prom-db
  namespace: aquasec-monitoring
spec:
  storageClassName: ocs-storagecluster-ceph-rdb
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
