apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      storageClassName: "ocs-storagecluster-ceph-rbd"
      size: 100Gi
  zookeeper:
    replicas: 3
    storage:
      storageClassName: "ocs-storagecluster-ceph-rbd"
      size: 100Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}

