apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
    machine.openshift.io/cluster-api-machineset: general-purpose-1a
  name: general-purpose-1a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
      machine.openshift.io/cluster-api-machineset: general-purpose-1a
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: general-purpose-1a
    spec:
      metadata:
        creationTimestamp: null
        labels:
          node-role.kubernetes.io/general-use: ""
      providerSpec:
        value:
          ami:
            id: ami-0543fbfb4749f3c3b
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 200
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ocp4c-8m8b7-worker-profile
          instanceType: m4.xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-1a
            region: us-east-1
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - ocp4c-8m8b7-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - ita-lab-priv-1
          tags:
          - name: kubernetes.io/cluster/ocp4c-8m8b7
            value: owned
          userDataSecret:
            name: worker-user-data
      versions:
        kubelet: ""
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
    machine.openshift.io/cluster-api-machineset: general-purpose-1c
  name: general-purpose-1c
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
      machine.openshift.io/cluster-api-machineset: general-purpose-1c
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: general-purpose-1c
    spec:
      metadata:
        creationTimestamp: null
        labels:
          node-role.kubernetes.io/general-use: ""
      providerSpec:
        value:
          ami:
            id: ami-0543fbfb4749f3c3b
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 200
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ocp4c-8m8b7-worker-profile
          instanceType: m4.xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-1C
            region: us-east-1
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - ocp4c-8m8b7-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - ita-lab-priv-1
          tags:
          - name: kubernetes.io/cluster/ocp4c-8m8b7
            value: owned
          userDataSecret:
            name: worker-user-data
      versions:
        kubelet: ""
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
    machine.openshift.io/cluster-api-machineset: general-purpose-1e
  name: general-purpose-1e
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
      machine.openshift.io/cluster-api-machineset: general-purpose-1e
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: general-purpose-1e
    spec:
      metadata:
        creationTimestamp: null
        labels:
          node-role.kubernetes.io/general-use: ""
      providerSpec:
        value:
          ami:
            id: ami-0543fbfb4749f3c3b
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 200
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ocp4c-8m8b7-worker-profile
          instanceType: m4.xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-1e
            region: us-east-1
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - ocp4c-8m8b7-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - ita-lab-priv-1
          tags:
          - name: kubernetes.io/cluster/ocp4c-8m8b7
            value: owned
          userDataSecret:
            name: worker-user-data
      versions:
        kubelet: ""