apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ldapidp 
    mappingMethod: claim 
    type: LDAP
    ldap:
      attributes:
        email: []
        id:
        - sAMAccountName
        name:
        - sAMAccountName
        preferredUsername:
        - sAMAccountName
      bindDN: "" 
      bindPassword: 
        name: ldap-secret
      # Add ca config map for certs: oc create configmap ca-config-map --from-file=ca.crt=/path/to/ca -n openshift-config
      # ca: 
      #  name: ca-config-map
      insecure: false 
      url: "ldap://<ldap-server-url>/ou=users,dc=acme,dc=com?uid" 