apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "ocs-registry-cephfs"
spec:
  storageClassName: "ocs-storagecluster-cephfs"
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "100Gi"
