apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "registry-pvc"
spec:
  storageClassName: "ocs-storagecluster-ceph-rbd"
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "300Gi"
