apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
    machine.openshift.io/cluster-api-machine-role: workerocs
    machine.openshift.io/cluster-api-machine-type: workerocs
  name: ocp4c-8m8b7-workerocs-us-east-1a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
      machine.openshift.io/cluster-api-machineset: ocp4c-8m8b7-workerocs-us-east-1a
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
        machine.openshift.io/cluster-api-machine-role: workerocs
        machine.openshift.io/cluster-api-machine-type: workerocs
        machine.openshift.io/cluster-api-machineset: ocp4c-8m8b7-workerocs-us-east-1a
    spec:
      metadata:
        creationTimestamp: null
        labels:
          role: storage-node
          node-role.kubernetes.io/worker: ""
          cluster.ocs.openshift.io/openshift-storage: ""
      providerSpec:
        value:
          ami:
            id: ami-0543fbfb4749f3c3b
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 2000
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ocp4c-8m8b7-worker-profile
          instanceType: m4.4xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-1a
            region: us-east-1
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - ocp4c-8m8b7-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - subnet-0326915d699f2be74
          tags:
          - name: kubernetes.io/cluster/ocp4c-8m8b7
            value: owned
          userDataSecret:
            name: worker-user-data
      versions:
        kubelet: ""
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
    machine.openshift.io/cluster-api-machine-role: workerocs
    machine.openshift.io/cluster-api-machine-type: workerocs
  name: ocp4c-8m8b7-workerocs-us-east-1e
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
      machine.openshift.io/cluster-api-machineset: ocp4c-8m8b7-workerocs-us-east-1e
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
        machine.openshift.io/cluster-api-machine-role: workerocs
        machine.openshift.io/cluster-api-machine-type: workerocs
        machine.openshift.io/cluster-api-machineset: ocp4c-8m8b7-workerocs-us-east-1e
    spec:
      metadata:
        creationTimestamp: null
        labels:
          role: storage-node
          node-role.kubernetes.io/worker: ""
          cluster.ocs.openshift.io/openshift-storage: ""
      providerSpec:
        value:
          ami:
            id: ami-0543fbfb4749f3c3b
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 2000
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ocp4c-8m8b7-worker-profile
          instanceType: m4.4xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-1e
            region: us-east-1
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - ocp4c-8m8b7-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - subnet-0c489a2536b4aa4ec
          tags:
          - name: kubernetes.io/cluster/ocp4c-8m8b7
            value: owned
          userDataSecret:
            name: worker-user-data
      versions:
        kubelet: ""
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
    machine.openshift.io/cluster-api-machine-role: workerocs
    machine.openshift.io/cluster-api-machine-type: workerocs
  name: ocp4c-8m8b7-workerocs-us-east-1c
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
      machine.openshift.io/cluster-api-machineset: ocp4c-8m8b7-workerocs-us-east-1c
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: ocp4c-8m8b7
        machine.openshift.io/cluster-api-machine-role: workerocs
        machine.openshift.io/cluster-api-machine-type: workerocs
        machine.openshift.io/cluster-api-machineset: ocp4c-8m8b7-workerocs-us-east-1c
    spec:
      metadata:
        creationTimestamp: null
        labels:
          role: storage-node
          node-role.kubernetes.io/worker: ""
          cluster.ocs.openshift.io/openshift-storage: ""
      providerSpec:
        value:
          ami:
            id: ami-0543fbfb4749f3c3b
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 2000
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ocp4c-8m8b7-worker-profile
          instanceType: m4.4xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-1c
            region: us-east-1
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - ocp4c-8m8b7-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - subnet-02b6bab5a7f49c217
          tags:
          - name: kubernetes.io/cluster/ocp4c-8m8b7
            value: owned
          userDataSecret:
            name: worker-user-data
      versions:
        kubelet: ""