apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-node-configmap
  namespace: aquasec-monitoring
data:
  prometheus-node-config.yaml: |
    global:
      scrape_interval: 15s

    scrape_configs:
    - job_name: node
      static_configs:
      - targets: ['ip-10-252-25-101.ec2.internal:9100']
