apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-up
  namespace: scale-up-test
  labels:
    app: scale-up
spec:
  replicas: 9 
  selector:
    matchLabels:
      app: scale-up
  template:
    metadata:
      labels:
        app: scale-up
    spec:
      containers:
      - name: busybox
        image: spnexus.lab.dtcc.com:7990/busybox:latest
        resources:
          requests:
            memory: 2Gi
      terminationGracePeriodSeconds: 0
