apiVersion: batch/v1
kind: Job
metadata:
  generateName: scale-up-job-work-queue-
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: spnexus.lab.dtcc.com:7990/busybox:latest
        command: ["sleep",  "300"]
        resources:
          requests:
            memory: 2Gi
            cpu: 300m
      restartPolicy: Never
      nodeSelector:
        node-role.kubernetes.io/worker: ""
  parallelism: 50
  completions: 50
